#! /bin/sh
#
# this should be cheaper than invoking "grep"
#
# usage: grep_stab device
#
# depends from: $SCRIPT_DIR, $SCRIPT_DBG,
#               $SCRIPT_DIR/shared/put_result
#
# returns: 0-success; 1-error
#          $SOCKET, $CLASS, $DRIVER, $INSTANCE, $MAJOR, $MINOR


[ $SCRIPT_DBG -eq 1 ] && echo " -> $SCRIPT_DIR/shared/grep_stab($1)"


while read SOCKET CLASS DRIVER INSTANCE L_DEV MAJOR MINOR ; do
  if [ "$SOCKET" != "Socket" -a "$1" = "$L_DEV" ] ; then 
    $SCRIPT_DIR/shared/put_result SOCKET   $SOCKET
    $SCRIPT_DIR/shared/put_result CLASS    $CLASS
    $SCRIPT_DIR/shared/put_result DRIVER   $DRIVER
    $SCRIPT_DIR/shared/put_result INSTANCE $INSTANCE
    $SCRIPT_DIR/shared/put_result MAJOR    $MAJOR
    $SCRIPT_DIR/shared/put_result MINOR    $MINOR

    [ $SCRIPT_DBG -eq 1 ] && echo " <- $SCRIPT_DIR/shared/get_info (ret=0)"
    exit 0
  fi
done


[ $SCRIPT_DBG -eq 1 ] && echo " <- $SCRIPT_DIR/shared/get_info (ret=1)"
exit 1

