#! /bin/sh
#
# usage: usage script_name
#
# depends from: $SCRIPT_DIR, $SCRIPT_DBG,
#
# returns: 0-success; 1-error


[ $SCRIPT_DBG -eq 1 ] && echo " -> $SCRIPT_DIR/shared/usage ($1)"

echo "usage: $1 [action] [device name]"
echo "  actions: start check stop suspend resume"

[ $SCRIPT_DBG -eq 1 ] && echo " <- $SCRIPT_DIR/shared/usage (ret=1)"
exit 1

