#!/bin/sh
#
# usage: dhcpd_up interface
#
# depends from: $DEBUG, $BIN, $SCRIPT
#               $BIN/cat
#               $BIN/rm
#               $BIN/udhcpd
#
# returns: 0-success;
#          1-Error: Wrong Interface
#          1-Error: External Command or File Is Not Available
#          1-Error: DHCPD is Already Started for This Interface
#          1-Error: Invalid Configuration File
#          2-TryAgain: The Access is Already Locked from Somebody Else


if [ -z "$DEBUG"  ] ; then DEBUG="/dev/null"  ; fi
if [ -z "$BIN"    ] ; then BIN="/bin"         ; fi
if [ -z "$SCRIPT" ] ; then SCRIPT="/etc"      ; fi

echo "-> $0 ($1)"                                                    >> $DEBUG


# Parameters check
if [ -z "$1" ] ; then
  echo "   $0 [ERR]: Wrong interface $1"                             >> $DEBUG
  echo "<- $0 (ret=1)"                                               >> $DEBUG
  exit 1
else
  INTF=$1
fi


# Set some constants
CFG_FILE="/var/rc/${INTF}_cfg"
LOCK_FILE="/var/rc/${INTF}_dhcpd_lock"
START_FILE="/var/rc/${INTF}_dhcpd"
INSTANCE_FILES="/var/rc/*_dhcpd"


# Checks the commands availavility
if [ ! -x "$BIN/rm" ] ; then
  echo "   $0 [ERR]: $BIN/rm is not available"                       >> $DEBUG
  echo "<- $0 (ret=1)"                                               >> $DEBUG
  exit 1
fi

if [ ! -x "$BIN/cat" ] ; then
  echo "   $0 [ERR]: $BIN/cat is not available"                      >> $DEBUG
  echo "<- $0 (ret=1)"                                               >> $DEBUG
  exit 1
fi

if [ ! -x "$BIN/udhcpd" ] ; then
  echo "   $0 [ERR]: $BIN/udhcpd is not available"                   >> $DEBUG
  echo "<- $0 (ret=1)"                                               >> $DEBUG
  exit 1
fi



# Lock the access 
if [ ! -f "$LOCK_FILE" ] ; then
  echo "$0"  >> "$LOCK_FILE"
else
  echo "   $0 [ERR]: The lock file $LOCK_FILE exists"                >> $DEBUG
  echo "<- $0 (ret=2)"                                               >> $DEBUG
  exit 2
fi


# Check for previous instances 
if [ -f "$START_FILE" ] ; then
  echo "   $0 [ERR]: DHCPD is already started for $INTF interface"   >> $DEBUG

  # Unlock the network access
  $BIN/rm $LOCK_FILE                                                 >> $DEBUG

  echo "<- $0 (ret=1)"                                               >> $DEBUG
  exit 1
fi

if [ ! -f "$INSTANCE_FILES" ] ; then
#  # Get the configuration
#  if [ -x "$CFG_FILE" ] ; then
#    . "$CFG_FILE"
#  else
#    echo "   $0 [ERR]: Invalid configuration file $CFG_FILE"          >> $DEBUG
#
#    # Unlock the network access
#    $BIN/rm $LOCK_FILE                                                >> $DEBUG
#
#    echo "<- $0 (ret=1)"                                              >> $DEBUG
#    exit 1
#  fi

  # Starts the DHCP server 
  echo "   $0 [INF]: Starts DHCP server"                             >> $DEBUG

  $BIN/cat /dev/null > /var/udhcpd.leases
  $BIN/udhcpd &

else
  echo "   $0 [INF]: DHCPD demon is already started once"            >> $DEBUG
fi


# Mark DHCPD started for this interface
if [ ! -f "$START_FILE" ] ; then
  echo "$0"  >> "$START_FILE"
else
  echo "   $0 [WRN]: The $START_FILE already exists"                 >> $DEBUG
fi


# Unlock the network access
$BIN/rm $LOCK_FILE                                                   >> $DEBUG

echo "<- $0 (ret=0)"                                                 >> $DEBUG
exit 0

